### ISSUE TITLE
Correct citation for all sources

### ISSUE THREAD

**Issue by fschmalzel** [Part-IO/visualize#12]
So far we have:

- GeoJSON | Source: ???
- Census | Source: https://www.statistikdaten.bayern.de/genesis//online?operation=table&code=12411-003r&bypass=true&levelindex=0&levelid=1638273219379#abreadcrumb
- Area | Source: https://www.statistikdaten.bayern.de/genesis//online?operation=table&code=33111-201r&bypass=true&levelindex=0&levelid=1638273244475#abreadcrumb and https://www.statistikdaten.bayern.de/genesis//online?operation=table&code=33111-001r&bypass=true&levelindex=0&levelid=1638273260896#abreadcrumb

**Comment by Mozartuss** [comment]
GeoJSON Source: https://gdz.bkg.bund.de/index.php/default/open-data/verwaltungsgebiete-1-250-000-ebenen-stand-31-12-vg250-ebenen-31-12.html
