### ISSUE TITLE
Research best chart library

### ISSUE THREAD

**Issue by Mozartuss** [Part-IO/visualize#24]

**Comment by Part-IO** [comment]
Suggest React Chart: https://react-charts.js.org/
1. Using Column Chart
2. Bubble Chart?

**Comment by fschmalzel** [comment]
This site doesn't exist, please fix.

**Comment by Part-IO** [comment]
Fixed https://github.com/reactchartjs/react-chartjs-2

**Comment by Part-IO** [comment]
https://github.com/apexcharts/react-apexcharts
