### ISSUE TITLE
Include Compare Area View / Button

### ISSUE THREAD

**Issue by Part-IO** [Part-IO/visualize#25]
It should be possible to select one area (e.g your hometown) and compare it to the different, available areas

Suggestion: One line or point for selected area with different color in each chart (Not MapView)

**Comment by Mozartuss** [comment]
Sounds Good, but only on the same hierarchy level (__countries ⇄ countries__  ~countries ⇄ government countries~)
And for this, we need a Popup view, or we have to transform the whole view to display the two charts next to each other.
Should the map be visible during the comparison?
