### ISSUE TITLE
Tooltip Information

### ISSUE THREAD

**Issue by Part-IO** [Part-IO/visualize#54]

**Comment by Part-IO** [comment]
@Mozartuss ich hab jetzt für die absolute Anzeige keine Veränderung und für prozentual sowohl die Prozent- als auch die Absolutzahl.

**Comment by Part-IO** [comment]
Oder was meintest du sonst?

**Comment by Mozartuss** [comment]
Würde bei den Absolut Werten auch die Prozentzahlen hin machen

**Comment by Mozartuss** [comment]
Vielleicht wäre ein anstiegsrate noch cool (im Schnitt steigt jährlich der Verbrauch um xy), wobei dann wieder mehr Daten geladen werden müssen 💁‍♂️

**Comment by Part-IO** [comment]
> Würde bei den Absolut Werten auch die Prozentzahlen hin machen

Jo kein Problem

**Comment by Part-IO** [comment]
> Vielleicht wäre ein anstiegsrate noch cool (im Schnitt steigt jährlich der Verbrauch um xy), wobei dann wieder mehr Daten geladen werden müssen 💁‍♂️

Fänd ich dann auch bisschen viele Informationen nur in einer kleinen Info Karte
