### ISSUE TITLE
Popup Layout Adaption - Scrollbar

### ISSUE THREAD

**Issue by Part-IO** [Part-IO/visualize#55]

**Comment by Mozartuss** [comment]
?

**Comment by Part-IO** [comment]
Beim Warning Popup verändert sich das Layout (die Scrollbar wird ausgeblendet)

**Comment by Mozartuss** [comment]
> Beim Warning Popup verändert sich das Layout (die Scrollbar wird ausgeblendet)

Dann schreib das doch XD
