### ISSUE TITLE
Sub-Sub Header Suggestions

### ISSUE THREAD

**Issue by Part-IO** [Part-IO/visualize#58]

**Comment by Part-IO** [comment]
Jeden Tag werden xx Fußballfelder in Bayern versiegelt

**Comment by Part-IO** [comment]
München bis 20?? weniger als 5% Naturfläche?

**Comment by Part-IO** [comment]
Bisher: Vollständige Versiegelung Münchens bis 2050?
--> Muss im Meeting bestimmt werden

**Comment by Mozartuss** [comment]
Es kann auch so ein Karussell durchlaufen wo dann aussagen drin stehen, die Zeitungen oder Webseite zu dem Thema prognostizieren.
So wie das bei Büchern oft ist 
![694702DA-3139-4C25-8469-A3FC75A7017C](https://user-images.githubusercontent.com/32893711/149682392-82fe1a21-24c9-417b-ada7-463c541cc946.jpeg)
